### ISSUE TITLE
TX message doesn't appear in view

### ISSUE THREAD

**Issue by jgressmann** [TDahlmann/canpp#2]
My setup uses two channels 1+2 and a third CAN-Interface that sends the frame with CAN-ID 0x123.

Both channels receive the CAN frames ok as shown in the picture. However, the message with CAN-ID 0x333 that gets transmitted by channel 1 isn't properly shown in the view. Instead, the view toggles between channel 1 TX and channel 2 RX.

The expected behaviour is to have two entries in the view, one for ch1 TX and one for ch2 RX.

Please see the attached picture for details.

![image](https://user-images.githubusercontent.com/8832225/117764548-f5f96700-b22c-11eb-87d3-3f4e89b22e4b.png)

**Comment by TDahlmann** [comment]
Due to missing 120 Ohm resistors I could not rebuilt this setup. But the issues schould be fixed with version 4.3.3. I encountered same problem with simple loopback setup.

**Comment by jgressmann** [comment]
Looks good.
