### ISSUE TITLE
CAN-FD DLC misleading

### ISSUE THREAD

**Issue by jgressmann** [TDahlmann/canpp#3]
When I try to setup a CAN-FD TX message withe a DLC of 15 as shown in the first image, the app will appear to be sending a FD message, but instead transmits a CAN 2.0 frame with a DLC of 8 (2nd image).

The app should block dlc > 8 if the FD flag isn't set or should auto-enable the flag to avoid confusion.

![image](https://user-images.githubusercontent.com/8832225/117766012-2e01a980-b22f-11eb-8eb2-f57892a585b6.png)
![image](https://user-images.githubusercontent.com/8832225/117766043-3c4fc580-b22f-11eb-9152-71b0f5963086.png)

**Comment by TDahlmann** [comment]
Should be fixed with version 4.3.3. Now if user puts in more than 8 bytes a warning messages shows up and FDF is set automatically. Furthermore it is checked whether channel is configured for CAN FD.

**Comment by jgressmann** [comment]
Looks good, however, the reverse doesn't hold.

The application should set DLC to 8 when FDF or FDF+BRS is disabled (None). What is worse is that the app shows an FD frame with DLC 10 but the frame on the bus is 8 byte classic CAN.

![image](https://user-images.githubusercontent.com/8832225/119128634-2ebbec00-ba36-11eb-9eee-2849ae72f9f0.png)
![image](https://user-images.githubusercontent.com/8832225/119128907-89554800-ba36-11eb-93f6-1142896b6712.png)

Bonus points: show the warning pop-up on top of the TX window, not the main app to avoid having to switch views. Consider having an "don't show this message again" option.

**Comment by TDahlmann** [comment]
Should be fixed with current pre view on develop branch. Bonus still todo. Maybe furthermore all TX entries should be checked on changing the channel type.

**Comment by jgressmann** [comment]
Looks good, thanks
