### ISSUE TITLE
error message pops up when not using all interfaces

### ISSUE THREAD

**Issue by jgressmann** [TDahlmann/canpp#4]
The error message pops up whenever the app goes on bus but doesn't have the second channel enabled.

Steps to reproduce:
1. plug in a multi-channel HW
2. Select only the first channel of the HW in the app
3. go on bus

![image](https://user-images.githubusercontent.com/8832225/117767960-f2b4aa00-b231-11eb-9967-7924d8d88c6a.png)
![1](https://user-images.githubusercontent.com/8832225/117767997-ff390280-b231-11eb-9b33-7095638a767b.PNG)

**Comment by TDahlmann** [comment]
I could not reproduce the issue so far.

**Comment by jgressmann** [comment]
Still present in 4.3.3.

Steps to reproduce with D5035-01:

1. Start the application
2. Select the channel dialog
3. Deselect channel 2 by means of the checkbox
4. Select channe1 (click on the line)
5. Select "Adjust bit timings" 
6. Click on apply

![image](https://user-images.githubusercontent.com/8832225/119126533-6aa18200-ba33-11eb-847c-90330cad0c6b.png)

**Comment by TDahlmann** [comment]
Now I could reproduce the issue. It does not occurr in a debug build so I dif not find it before when I used debug builds only. There seems to be some race condition which I have to find. In progress ...

**Comment by TDahlmann** [comment]
Should be fixed in version 4.3.4 on master branch.
The thread of the disabled channel was running without any delay so causing heavy CPU usage and making thread stopping difficult.

**Comment by jgressmann** [comment]
Looks good in 4.3.4
