### ISSUE TITLE
Application permits TX frame configuration with invalid DLC

### ISSUE THREAD

**Issue by jgressmann** [TDahlmann/canpp#6]
The application should clamp the user input to the closes possible valid DLC value.

![image](https://user-images.githubusercontent.com/8832225/119130754-e5b96700-ba38-11eb-954c-e95f424afcb1.png)

**Comment by TDahlmann** [comment]
Should be fixed in version 4.3.4 on master branch.

**Comment by jgressmann** [comment]
Looks good in 4.3.4
